import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-br from-gray-950 via-slate-900 to-black text-white`}>
        <main className="mx-auto max-w-3xl px-4 py-8">
          <header className="mb-6 flex items-center justify-between">
            <h1 className="text-2xl font-bold">Auth Todo</h1>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
